acme_store_product:
    resource: "@AcmeStoreBundle/Controller/ProductController.php"
    type:     annotation

acme_store_category:
    resource: "@AcmeStoreBundle/Controller/CategoryController.php"
    type:     annotation

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
